### ISSUE TITLE
Add .travis.yml

### ISSUE THREAD

**Issue by codenameyau** [codenameyau/scaffold-js#4]
This is slightly trickier to create since there are different versions of node with different project configurations to test against. Here's a boilerplate.

http://docs.travis-ci.com/user/languages/javascript-with-nodejs/

``` yaml
language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
  - "iojs-v1.0.4"

services:
  - mongodb

env:
  global:
    - CAMPFIRE_TOKEN=abc123
    - TIMEOUT=1000
  matrix:
    - USE_NETWORK=true
    - USE_NETWORK=false
```
